from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BaseAdapter(Protocol):
    def query(self, action: str, params: dict) -> tuple[Any, bool]: ...  # (result, cached)
    def refresh(self) -> None: ...
    def health(self) -> dict: ...
    def permissions(self) -> dict: ...
    def describe(self) -> dict: ...
